### ISSUE TITLE
suggestion: investigate an s2i workflow for building the database builder image

### ISSUE THREAD

**Issue by tmckayus** [rebeccaSimmonds19/WineMapDatabase#3]
If we set up a template for an s2i workflow to generate the database loader image and launch it, users could clone the repo and modify the data csv and then relaunch.  It could even go the extra step and setup up github triggers for auto-update.

Maybe a phase 2 type modification

**Comment by rebeccaSimmonds19** [comment]
Decided to leave the workflow as it is as the loader is a job
